name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      description: What type of bug is this?
      options:
        - Component not working
        - Pipe not formatting correctly
        - Service method failing
        - Directive not applying
        - Build/Compilation error
        - TypeScript error
        - Runtime error
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Code Example
      description: If applicable, add code examples to help explain your problem.
      placeholder: |
        ```typescript
        // Your code here
        ```
      render: typescript

  - type: input
    id: angular-version
    attributes:
      label: Angular Version
      description: What version of Angular are you using?
      placeholder: e.g., 19.0.0, 20.0.0
    validations:
      required: true

  - type: input
    id: library-version
    attributes:
      label: Angular Temporal Version
      description: What version of angular-temporal are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages
      description: If there are any error messages, please include them here.
      placeholder: |
        ```
        Error: ...
        ```

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment.
      placeholder: |
        - OS: [e.g., Windows 10, macOS 12, Ubuntu 20.04]
        - Node.js version: [e.g., 18.17.0, 20.5.0]
        - Browser: [e.g., Chrome 95, Firefox 94, Safari 15]
        - Angular CLI version: [e.g., 17.0.0]

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
